name: Run tests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - uses: browser-actions/setup-chrome@v1
        id: chromedriver
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: test
        env:
          CHROME_BIN: ${{ steps.chromedriver.outputs.chrome-path }}
        run: |
          output="$(npm run test:ci)"
          echo "$output"

          {
            echo "output<<EOF"
            echo "$output" | sed "s/>/\\\\>/g"
            echo "EOF"
          } >> "$GITHUB_OUTPUT""

      - name: Extract coverage
        run: |
          coverage=$(echo "${{ steps.test.outputs.output }}" | sed -n '/Coverage summary/,$p')
          has_coverage=$(test "$coverage" != "" && echo true || echo false)
          echo "has-coverage='$has_coverage'" >> $GITHUB_OUTPUT
          echo "coverage='$coverage'" >> $GITHUB_OUTPUT
